# Generated by Django 5.0.3 on 2024-04-11 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_patient_user_patient_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('GP', 'General Practitioner'), ('SP', 'Specialist'), ('SD', 'Surgeon'), ('OBGYN', 'Obstetrician/Gynecologist'), ('PED', 'Pediatrician'), ('ORTHO', 'Orthopedic Surgeon'), ('CARD', 'Cardiologist'), ('DERM', 'Dermatologist'), ('ENT', 'Otolaryngologist (ENT)'), ('NEURO', 'Neurologist'), ('PSY', 'Psychiatrist'), ('URO', 'Urologist')], max_length=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('O', 'Other')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
