# Generated by Django 5.0.3 on 2024-04-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('GP', 'General Practitioner'), ('SP', 'Specialist'), ('SUR', 'Surgeon'), ('OPHT', 'ophthalmologist'), ('OBGYN', 'Obstetrician/Gynecologist'), ('PED', 'Pediatrician'), ('ORTHO', 'Orthopedic Surgeon'), ('CARD', 'Cardiologist'), ('DERM', 'Dermatologist'), ('ENT', 'Otolaryngologist (ENT)'), ('NEURO', 'Neurologist'), ('PSY', 'Psychiatrist'), ('URO', 'Urologist')], max_length=5),
        ),
    ]
