# Generated by Django 5.0.3 on 2024-05-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('out_of_stock', 'Out of Stock')], default='available', max_length=20)),
            ],
        ),
    ]
